package com.hb.tile;

public enum WallType {
	FELSO,ALSO,JOBB,BAL,JOBBFELSO,JOBBALSO,BALALSO,BALFELSO,FOLD,REPEDTFOLD,FENTROLKILEP,JOBBROLKILEP,BALROLKILEP,ALULROLKILEP,JOBBROLVEGE,BALLROLVEGE,LENTROLVEGE,FENTROLVEGE;
}
